proxy_location: EveryNode

http_options:
  host: 0.0.0.0
  port: 8000

grpc_options:
  port: 9000
  grpc_servicer_functions: []

logging_config:
  encoding: TEXT
  log_level: INFO
  logs_dir: null
  enable_access_log: true
  additional_log_standard_attrs: []

applications:

- name: catboost-iris-classifier
  route_prefix: /catboost-iris-classifier
  import_path: app:app
  runtime_env: {
    env_vars: {
      MODEL_URI: "models:/catboost-iris-classifier/1"
    },
    pip: {
      packages: [
        "catboost==1.2.8",
        "numpy==2.0.2",
        "pandas==2.2.3"
      ]
    }
  }
  deployments:
  - name: App
    num_replicas: 2
    ray_actor_options:
      num_cpus: 0.2
      num_gpus: 0.0

- name: old-catboost-iris-classifier
  route_prefix: /old-catboost-iris-classifier
  import_path: app:app
  runtime_env: {
    env_vars: {
      MODEL_URI: "models:/old-catboost-iris-classifier/1"
    },
    pip: {
      packages: [
        "catboost==1.1",
        "numpy==1.26.4",
        "pandas==1.5.3"
      ]
    }
  }
  deployments:
  - name: App
    num_replicas: 2
    ray_actor_options:
      num_cpus: 0.2
      num_gpus: 0.0
