applications:
- deployments:
  - name: App
    num_replicas: 1
    ray_actor_options:
      memory: 1.0
      num_cpus: 0.5
  import_path: mlray.app:app
  name: iris_classifier-py39-catboost11
  route_prefix: /iris_classifier-py39-catboost11
  runtime_env:
    env_vars:
      MLFLOW_TRACKING_URI: http://mlflow-server:8080
      MODEL_URI: models:/iris_classifier-py39-catboost11/1
    pip:
    - mlflow==3.1.0
    - catboost==1.1
    - ipython==8.18.1
    - numpy==1.26.4
    - pandas==1.5.3
    - scipy==1.13.1
- deployments:
  - name: App
    num_replicas: 1
    ray_actor_options:
      memory: 1.0
      num_cpus: 0.5
  import_path: mlray.app:app
  name: iris_classifier-py39-catboost12
  route_prefix: /iris_classifier-py39-catboost12
  runtime_env:
    env_vars:
      MLFLOW_TRACKING_URI: http://mlflow-server:8080
      MODEL_URI: models:/iris_classifier-py39-catboost12/1
    pip:
    - mlflow==3.1.0
    - catboost==1.2.8
    - ipython==8.18.1
    - numpy==2.0.2
    - pandas==2.3.0
    - scipy==1.13.1
grpc_options:
  grpc_servicer_functions: []
  port: 9000
http_options:
  host: 0.0.0.0
  port: 8000
logging_config:
  additional_log_standard_attrs: []
  enable_access_log: true
  encoding: TEXT
  log_level: INFO
  logs_dir: null
proxy_location: EveryNode
